
name: Deploy website via FTP

on:
  push:
    branches:
      - deploy  # O la rama que estés utilizando para los despliegues

jobs:
  deploy:
    name: Deploy to FTP server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.1'  # O la versión de Node.js que uses

    - name: Install dependencies
      run: npm install

    - name: Build the website
      run: npm run build

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/  # Cambia esto si tu carpeta de salida es diferente
        server-dir: /  # Cambia esto por la ruta en tu servidor FTP
        exclude: |
          **/.git*
          **/node_modules/**
